create-lines:
	python -m app.commands.create_lines

create-stops:
	python -m app.commands.create_stops

test:
	pytest tests/ --cov --cov-config=tests/.coveragerc --cov-report html:tests/htmlcov

open-coverage:
	open tests/htmlcov/index.html